name: Indexing API

on:
  push:
    branches:
      - main

jobs:
  indexing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Crear archivo sa.json desde secret base64
        run: |
          echo "$GOOGLE_SERVICE_ACCOUNT_JSON_BASE64" | base64 -d > sa.json

      - name: Instalar dependencias Python
        run: pip install google-auth google-api-python-client

      - name: Ejecutar script de indexing
        run: python index.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS: sa.json
