name: Google Indexing API

on:
  workflow_dispatch:

jobs:
  indexing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Crear archivo sa.json con credenciales
      run: |
        echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON_BASE64 }}" | base64 --decode > sa.json

    - name: Verificar contenido de sa.json
      run: head -20 sa.json

    - name: Instalar dependencias Python
      run: |
        python -m pip install --upgrade pip
        pip install google-auth google-auth-httplib2 google-auth-oauthlib google-api-python-client

    - name: Ejecutar script Python de indexación
      run: python index.py

